### ISSUE TITLE
Make more GIFs

### ISSUE THREAD

**Issue by ignatov** [controlflow/intellij-postfix#13]
GIFs are cool :)

**Comment by zolotov** [comment]
Damn completion popup makes some artefacts on gifs :(

Foreach
![foreach](https://f.cloud.github.com/assets/140920/1763649/089d45aa-6714-11e3-948d-87c4419ed1e6.gif)

For
![fori_forr](https://f.cloud.github.com/assets/140920/1763650/089e6282-6714-11e3-9e98-ba45657f868b.gif)

If
![if_cast](https://f.cloud.github.com/assets/140920/1763651/08b4ec00-6714-11e3-94c0-80b02aca2934.gif)

Instanceof
![instanceof](https://f.cloud.github.com/assets/140920/1763652/08b5641e-6714-11e3-98cb-7c4f11bb8920.gif)

NotNull
![not_null](https://f.cloud.github.com/assets/140920/1763653/08c74256-6714-11e3-96e3-b6525b8d5852.gif)

While
![while](https://f.cloud.github.com/assets/140920/1763654/08c800a6-6714-11e3-9eeb-028f005f1f05.gif)

**Comment by zolotov** [comment]
Close the issue if it's enough :)

**Comment by zolotov** [comment]
Make gif for .not template:

``` java
if (list.isEmpty() && another.isEmpty().not<caret>) {
```
