### ISSUE TITLE
When findviewbyid error occurred

### ISSUE THREAD

**Issue by HeykelWu** [controlflow/intellij-postfix#20]
![qq 20160907145249](https://cloud.githubusercontent.com/assets/15372677/18302849/b04a465a-750c-11e6-8dd6-d38f70e3bb62.png)

**Comment by zolotov** [comment]
this repo has nothing to do with Android Postfix Completion. See https://plugins.jetbrains.com/plugin/7775?pr=idea

**Comment by HeykelWu** [comment]
i got it
